compile.on.save=true
do.depend=false
do.jar=true
file.reference.mysql-connector-j-9.4.0.jar=C:\\Users\\madha\\Pictures\\Documents\\mysql-connector-j-9.4.0.jar
javac.debug=true
javadoc.preview=true
user.properties.file=C:\\Users\\madha\\AppData\\Roaming\\NetBeans\\7.4\\build.properties
